version: "3.8"
services:
    frontend:
        build: 
         context: .
         args:
            BACKEND_URL: ${BACKEND_URL}
        image: frontend:production
        ports:
           - "80:80"
networks:
    default:
       external:
          name: integrated-network
