version: "3.8"
services:
    frontend:
        build: .
        image: frontend:production
        ports:
           - "80:80"
networks:
    default:
       external:
          name: integrated-network
