version: "3.8"
services:
    frontend:
        build: .
        image: frontend:production
        ports:
           - "80:80"
        environment:
           - NODE_ENV=production
           - BACKEND_URL=${BACKEND_URL}
networks:
    default:
       external:
          name: integrated-network
